config/routes.rb
Splurty::Application.routes.draw do

  root 'quotes#index'
  resources :quotes
  get 'about', :to => 'quotes#about'
   

end

app/models/quote.rb
class Quote < ActiveRecord::Base
  validates :saying , :presence => true, :length => { :maximum => 140, :minimum => 3 }
  validates :author,  :presence => true, :length => { :maximum => 50,  :minimum => 3 }

  def unique_tag
    initials = self.author.split(' ').collect{ |sub_string| sub_string[0] }.join()
    initials + '#' + self.id.to_s
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  def index
    @quote = Quote.order("RANDOM()").first
  end

  def create
    @quote = Quote.create(quote_params)
    if @quote.invalid?
      flash[:error] = '<strong>Could not save</strong> the data you entered is invalid.'
    end
    redirect_to root_path
  end

  def about

  end

  def show
    @quote = Quote.where(:id => params[:id]).first
    if @quote.blank?
      render :text => "Not found", :status => :not_found
    end
  end

  private

  def quote_params
    params.require(:quote).permit(:saying, :author)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Splurty</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header>
    <div class="col-xs-3">
    <%= link_to root_path, :class => 'logo' do %>
      <div class="circle">
        <br />
        YOLO
        <br />
        LOL
        <br />
        OMG
      </div>
    <% end %>  
    </div>
    <div class="col-sm-4 hidden-xs slogan">
      Splurting out unsolicited advice about entrepreneurship since 2014
    </div>
    <div class="col-xs-8 col-xs-offset-1 col-sm-offset-0 col-sm-5 links">
      <%= link_to 'Contribute','#', :data => {:toggle => "modal", :target => "#myModal"} %>&nbsp;&nbsp;
      <%= link_to 'About', about_path %>
    </div>
  </header>
  <!-- Modal -->
  <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 class="modal-title" id="myModalLabel">Contribute your Quote</h4>
        </div>
        <%= simple_form_for Quote.new do |f| %>
          <div class="modal-body">
            <%= f.input :saying,
                 :label => "What is the saying you want to add ?",
                 :placeholder => "Fear is the disease. Hustle is the antidote"
                  %>
            <br />
            <%= f.input :author,
                :label => "Who is the author of the quote ?",
                :placeholder => "Travis Kalanick" %>
            <br/>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            <%= f.submit 'Create', :class => 'btn btn-danger' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <hr />
  <br class="clear">
  <div class="container">
    <div>
      <% if flash[:error].present? %>
      <div class="col-xs-10 col-xs-offset-1 alert alert-danger">
        <%= flash[:error].html_safe %>
      </div>
      <% end %>
    </div>
    <%= yield %>
  </div>
  <footer class="footer">
    <div class="container">
      <div class="col-xs-12 col-sm-6">
        <%= link_to "This isn't enough for me , I need more", root_path , :class => 'next-quote'  %>
      </div>
      <div class="col-xs-12 col-sm-6 footer-blurb">
        Proudly hacked in Boston, MA by <a href="http://thefirehoseproject.com">Marco &amp; Ken</a><br />
        Want to build your own Splurty Web App - <a href="http://thefirehoseproject.com">Learn how to code here</a>
      </div>
    </div>
  </footer>
</body>
</html>

app/views/quotes/about.html.erb
<div class="col-xs-10 col-xs-offset-1 about">
  <h1>About Splurty</h1>
  <p>
    Splurty was built by <a target="_blank" href="http://github.com/MarcoMorawec">Marco</a> &amp; <a target="_blank" href="http://github.com/KenMazaika">Ken</a>. Two web developers who are on a mission to give people the technical skills needed to launch their own MVPs and turn ideas into reality.
  </p>
  <br />
  <p>
    Together they taught hundreds of students how to code and build products people want at places like Harvard Business School, Carnegie Mellon, Babson, Rhode Island School of Design, Brown University, Punohou High School and ‘Iolani High School.
  </p>
  <p>
    If you want to learn how to code - start <a target="_blank" href="http://www.thefirehoseproject.com/"> here</a>.
  </p>
  <div class="col-xs-12 col-sm-4">
    <%= image_tag 'marco.jpeg', :class => 'img-responsive' %>
  </div>

  <div class="col-xs-12 col-sm-7 col-sm-offset-1">
    <h2 class="text-center">Marco Morawec</h2>
    <br />
    <p>
      Marco Morawec is a web developer and user experience product manager. He consulted Fortune 500 companies like P&amp;G and John Deere, won Boston's biggest Hackathon (<a target="_blank" href="http://www.angelhack.com/">Angelhack</a>) and most recently led the user experience for <a target="_blank" href="https://www.peertransfer.com/">peerTransfer</a>, building a $500M/year international tuition payment platform. In an earlier life, he travelled around the world on <a target="_blank" href="http://25dollartravel.com">$25/day</a> for an entire year.
    </p>
  </div>
  <br class="clear" />

  <div class="col-xs-12 col-sm-4" style="padding-top:30px;">
    <%= image_tag 'ken.jpeg', :class => 'img-responsive' %>
  </div>
  <div class="col-xs-12 col-sm-7 col-sm-offset-1">
    <h2 class="text-center">Ken Mazaika</h2>
    <br />
    <p>
      Ken Mazaika is a web developer and Ruby on Rails contributor. Previously he was a tech lead at Where.com (<a target="_blank" href="http://bostinno.streetwise.co/2011/04/13/nearbuys-where-rolls-out-daily-deals/">acquired by PayPal</a>) and a member of the PayPal/eBay development team in Boston. In a previous life he turned a <a target="_blank" href="http://yourfreequotes.com/">health insurance quotes generator</a> from a $400/day web application into a $40,000/day business.
    </p>
  </div>
</div>

<br class="clear" />
<br />
<br />
<br />
<br />

app/views/quotes/index.html.erb
<h2>
  <span>SPLURTY / No. <%= @quote.unique_tag %></span>
  Here's the <u>best unsolicited startup advice</u> you can get!
</h2>

<h1><%= @quote.saying %></h1>
<h2 class="pull-right">- <%= @quote.author %></h2>

<br class="clear" />
<br />
<br />
<br />

app/views/quotes/show.html.erb
<h1>Quote Details</h1>
<h2>
  <span>SPLURTY / <%= @quote.unique_tag %></span>
  Here's the <u>best unsolicited startup advice</u> you can get!
</h2>

<h1><%= @quote.saying %></h1>
<h2 class="pull-right">- <%= @quote.author %></h2>

<br class="clear" />
<br />
<br />
<br />